### ISSUE TITLE
NOT REGISTERING FUNCTIONS

### ISSUE THREAD

**Issue by landrew23** [learn-co-curriculum/phase-0-pac-3-arithmetic-lab#10]
### Canvas Link

git@github.com:landrew23/phase-0-pac-3-arithmetic-lab.git

### Concern

Visual Studio Code keeps saying that functions I declare are undefined even though I'm describing them perfectly in index.js.

**Comment by lizbur10** [comment]
Hi @landrew23 ! I am not able to reproduce this problem so it may be an issue with your local environment or your code rather than the lesson itself. 

If you are still having difficulties, I suggest that you use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team. 

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved!
