### ISSUE TITLE
I can't submit my calculator lab

### ISSUE THREAD

**Issue by tfink1975** [learn-co-curriculum/phase-0-pac-3-arithmetic-lab#6]
### Canvas Link

https://learning.flatironschool.com/courses/5290/assignments/165391?module_item_id=356921

### Concern

I can't make a submission for the calculator lab.

**Comment by lizbur10** [comment]
Thanks for raising this issue. This problem is likely to be related to your environment setup rather than with the lesson itself or the instructions. The curriculum team monitors these issues so that we can fix typos and bugs in the curriculum, but we aren't equipped to provide support.

To get help with your question, you can either post in the #js-prework-support Slack channel or use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team.

Hope you are able to get this resolved!
